# component2/SConscript
Import('env')
import os
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())



# if 'CONFIG_DEVICE_DRIVER_ENABLED' in os.environ:
SRCS=[AFile('src/lib1.c')]
# SRCS = ['source1.cpp', 'source2.cpp']
INCLUDE=[ADir('include')]
PRIVATE_INCLUDE=[]
REQUIREMENTS=['m']
STATIC_LIB=[]
DYNAMIC_LIB=[]
DEFINITIONS=['-DAAAAA222=1', '-DAAAAA333=1']
DEFINITIONS_PRIVATE=['-DAAAAA=1']
LDFLAGS=[]
LINK_SEARCH_PATH=[]




env['COMPONENTS'].append({'target':os.path.basename(env['component_dir']),
                        'SRCS':SRCS,
                        'INCLUDE':INCLUDE,
                        'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                        'REQUIREMENTS':REQUIREMENTS,
                        'STATIC_LIB':STATIC_LIB,
                        'DYNAMIC_LIB':DYNAMIC_LIB,
                        'DEFINITIONS':DEFINITIONS,
                        'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                        'LDFLAGS':LDFLAGS,
                        'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                        'REGISTER':'static'
                        })
