# Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib)

#
# Toolchain configuration
#
CONFIG_TOOLCHAIN_PATH="F:\\aapstar\\gcc\\mingw32\\bin"
CONFIG_TOOLCHAIN_PREFIX="./"
# end of Toolchain configuration

#
# Components configuration
#

#
# Component1 configuration
#
# CONFIG_COMPONENT1_INCLUDE_STATIC_LIB is not set
# end of Component1 configuration

#
# Component2 configuration
#
CONFIG_COMPONENT2_ENABLED=y

#
# Component2 configuration menu2
#
CONFIG_COMPONENT2_TEST_STR1=y
# CONFIG_COMPONENT2_TEST_STR2 is not set
# CONFIG_COMPONENT2_TEST_STR3 is not set
# end of Component2 configuration menu2
# end of Component2 configuration

# CONFIG_MENUCONFIG_EXAMPLE is not set
CONFIG_COMPONENT3_ENABLED=y
CONFIG_COMPONENT3_DYNAMIC=y
# end of Components configuration
